"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowLeft, ArrowUp, Check, Eye, LayoutDashboard, LockKeyhole, Monitor, Palette, Redo2, RotateCcw, Save, Settings2, Smartphone, Type, Undo2 } from "lucide-react";
import { SITE_CONFIG_STORAGE_KEY, useSiteSettings } from "@/features/site-settings/SiteSettingsProvider";
import { defaultSiteConfig, HomeSectionKey, mergeSiteConfig, SiteConfig } from "@/types/site-config";

const sectionLabels: Record<HomeSectionKey, string> = { identity: "활동명·분야", upload: "통합 자료 업로드", link: "공식 링크", aiStatus: "AI 분석 상태", trust: "신뢰 안내" };

export default function SiteAdminPage() {
  const { config: current, setPreview } = useSiteSettings();
  const [draft, setDraft] = useState<SiteConfig>(current);
  const [history, setHistory] = useState<SiteConfig[]>([]);
  const [future, setFuture] = useState<SiteConfig[]>([]);
  const [tab, setTab] = useState<"brand" | "home" | "team" | "layout">("brand");
  const [device, setDevice] = useState<"desktop" | "mobile">("desktop");
  const [password, setPassword] = useState("");
  const [notice, setNotice] = useState("설정을 수정하면 오른쪽 미리보기에 즉시 반영됩니다.");
  const [publishing, setPublishing] = useState(false);

  useEffect(() => { setDraft(current); }, [current]);
  const commit = (next: SiteConfig) => { setHistory((items) => [...items.slice(-29), draft]); setFuture([]); setDraft(next); setPreview(next); };
  const patch = <K extends keyof SiteConfig>(key: K, value: SiteConfig[K]) => commit({ ...draft, [key]: value });
  const undo = () => { const previous = history.at(-1); if (!previous) return; setFuture((items) => [draft, ...items]); setHistory((items) => items.slice(0, -1)); setDraft(previous); setPreview(previous); };
  const redo = () => { const next = future[0]; if (!next) return; setHistory((items) => [...items, draft]); setFuture((items) => items.slice(1)); setDraft(next); setPreview(next); };
  const reset = () => { commit(defaultSiteConfig); setNotice("기본 디자인으로 되돌렸습니다. 저장 전에는 사용자에게 게시되지 않습니다."); };
  const saveLocal = () => { localStorage.setItem(SITE_CONFIG_STORAGE_KEY, JSON.stringify(draft)); setPreview(draft); setNotice("이 브라우저에 작업본을 저장했습니다."); };
  const publish = async () => {
    setPublishing(true); setNotice("");
    try {
      const response = await fetch("/api/site-settings", { method: "PUT", headers: { "Content-Type": "application/json", Authorization: `Bearer ${password}` }, body: JSON.stringify(draft) });
      const result = await response.json();
      if (!response.ok) throw new Error(result.code === "LOCAL_PREVIEW_ONLY" ? "공용 게시를 사용하려면 Supabase와 ADMIN_PASSWORD를 연결해 주세요. 현재 작업본은 로컬 저장할 수 있습니다." : result.error);
      const saved = mergeSiteConfig(result.config); localStorage.setItem(SITE_CONFIG_STORAGE_KEY, JSON.stringify(saved)); setDraft(saved); setPreview(saved); setNotice("사이트 설정을 전체 사용자에게 게시했습니다.");
    } catch (error) { setNotice(error instanceof Error ? error.message : "게시하지 못했습니다."); }
    finally { setPublishing(false); }
  };
  const moveSection = (index: number, direction: -1 | 1) => {
    const target = index + direction; if (target < 0 || target >= draft.home.sections.length) return;
    const sections = [...draft.home.sections]; [sections[index], sections[target]] = [sections[target], sections[index]];
    patch("home", { ...draft.home, sections });
  };

  return <main className="cms-shell">
    <aside className="cms-side"><Link className="admin-brand" href="/"><span>{draft.brand.mark}</span> {draft.brand.name}</Link><nav><small>SITE EDITOR</small><button className={tab === "brand" ? "selected" : ""} onClick={() => setTab("brand")}><Palette /> 브랜드·색상</button><button className={tab === "home" ? "selected" : ""} onClick={() => setTab("home")}><Type /> 프로필 첫 화면</button><button className={tab === "team" ? "selected" : ""} onClick={() => setTab("team")}><LayoutDashboard /> 팀원 게시판</button><button className={tab === "layout" ? "selected" : ""} onClick={() => setTab("layout")}><Settings2 /> 레이아웃·노출</button><small>SHORTCUTS</small><Link href="/">프로필 제작 보기</Link><Link href="/team">팀원 게시판 보기</Link></nav><div className="cms-admin"><span>AD</span><div><strong>사이트 관리자</strong><small>디자인 편집 권한</small></div></div></aside>
    <section className="cms-workspace"><header><div><Link href="/"><ArrowLeft /> 사용자 화면</Link><h1>사이트 디자인 편집</h1><p>문구·브랜드·섹션 순서와 화면 스타일을 코드 없이 관리합니다.</p></div><div className="cms-history"><button disabled={!history.length} onClick={undo}><Undo2 /> 실행 취소</button><button disabled={!future.length} onClick={redo}><Redo2 /> 다시 실행</button><button onClick={reset}><RotateCcw /> 초기화</button></div></header>
      <div className="cms-grid"><section className="cms-controls">
        {tab === "brand" && <><EditorGroup title="브랜드"><TextField label="서비스 이름" value={draft.brand.name} onChange={(name) => patch("brand", { ...draft.brand, name })} /><TextField label="로고 글자" value={draft.brand.mark} maxLength={3} onChange={(mark) => patch("brand", { ...draft.brand, mark })} /><TextField label="브랜드 설명" value={draft.brand.tagline} onChange={(tagline) => patch("brand", { ...draft.brand, tagline })} /></EditorGroup><EditorGroup title="색상 시스템"><div className="cms-color-grid"><ColorField label="주 색상" value={draft.theme.primary} onChange={(primary) => patch("theme", { ...draft.theme, primary })} /><ColorField label="강조 색상" value={draft.theme.accent} onChange={(accent) => patch("theme", { ...draft.theme, accent })} /><ColorField label="본문 색상" value={draft.theme.ink} onChange={(ink) => patch("theme", { ...draft.theme, ink })} /><ColorField label="배경 색상" value={draft.theme.paper} onChange={(paper) => patch("theme", { ...draft.theme, paper })} /><ColorField label="카드 색상" value={draft.theme.surface} onChange={(surface) => patch("theme", { ...draft.theme, surface })} /></div></EditorGroup><EditorGroup title="상단 메뉴"><TextField label="프로필 메뉴" value={draft.navigation.studio} onChange={(studio) => patch("navigation", { ...draft.navigation, studio })} /><TextField label="팀 메뉴" value={draft.navigation.team} onChange={(team) => patch("navigation", { ...draft.navigation, team })} /><TextField label="관리 메뉴" value={draft.navigation.admin} onChange={(admin) => patch("navigation", { ...draft.navigation, admin })} /></EditorGroup></>}
        {tab === "home" && <><EditorGroup title="첫 화면 문구"><TextField label="작은 제목" value={draft.home.eyebrow} onChange={(eyebrow) => patch("home", { ...draft.home, eyebrow })} /><TextField label="메인 제목" value={draft.home.title} onChange={(title) => patch("home", { ...draft.home, title })} /><TextField label="강조 제목" value={draft.home.accentTitle} onChange={(accentTitle) => patch("home", { ...draft.home, accentTitle })} /><TextArea label="설명" value={draft.home.description} onChange={(description) => patch("home", { ...draft.home, description })} /></EditorGroup><EditorGroup title="업로드 영역"><TextField label="업로드 제목" value={draft.home.uploadTitle} onChange={(uploadTitle) => patch("home", { ...draft.home, uploadTitle })} /><TextField label="업로드 안내" value={draft.home.uploadDescription} onChange={(uploadDescription) => patch("home", { ...draft.home, uploadDescription })} /><TextField label="자료 없음 버튼" value={draft.home.noMaterialLabel} onChange={(noMaterialLabel) => patch("home", { ...draft.home, noMaterialLabel })} /></EditorGroup><EditorGroup title="하단 신뢰 문구">{draft.home.trustItems.map((item, index) => <TextField label={`문구 ${index + 1}`} value={item} key={index} onChange={(value) => { const trustItems = [...draft.home.trustItems]; trustItems[index] = value; patch("home", { ...draft.home, trustItems }); }} />)}</EditorGroup></>}
        {tab === "team" && <><EditorGroup title="게시판 첫 화면"><TextField label="작은 제목" value={draft.team.eyebrow} onChange={(eyebrow) => patch("team", { ...draft.team, eyebrow })} /><TextArea label="메인 제목" value={draft.team.title} onChange={(title) => patch("team", { ...draft.team, title })} /><TextArea label="설명" value={draft.team.description} onChange={(description) => patch("team", { ...draft.team, description })} /><TextField label="작성 버튼" value={draft.team.createLabel} onChange={(createLabel) => patch("team", { ...draft.team, createLabel })} /><TextField label="검색창 안내" value={draft.team.searchPlaceholder} onChange={(searchPlaceholder) => patch("team", { ...draft.team, searchPlaceholder })} /></EditorGroup><EditorGroup title="콘텐츠 정책"><Toggle label="예시 모집글 표시" checked={draft.team.showDemoPosts} onChange={(showDemoPosts) => patch("team", { ...draft.team, showDemoPosts })} /></EditorGroup></>}
        {tab === "layout" && <><EditorGroup title="전체 화면"><RangeField label="콘텐츠 최대 폭" value={draft.theme.contentWidth} min={900} max={1500} suffix="px" onChange={(contentWidth) => patch("theme", { ...draft.theme, contentWidth })} /><RangeField label="카드 모서리" value={draft.theme.radius} min={0} max={36} suffix="px" onChange={(radius) => patch("theme", { ...draft.theme, radius })} /><RangeField label="글자 배율" value={draft.theme.fontScale} min={85} max={120} suffix="%" onChange={(fontScale) => patch("theme", { ...draft.theme, fontScale })} /><label className="cms-field"><span>헤더 스타일</span><select value={draft.theme.headerStyle} onChange={(event) => patch("theme", { ...draft.theme, headerStyle: event.target.value as "solid" | "glass" })}><option value="glass">반투명 글래스</option><option value="solid">단색 헤더</option></select></label></EditorGroup><EditorGroup title="프로필 첫 화면 섹션 순서"><div className="cms-section-list">{draft.home.sections.map((section, index) => <article key={section.key}><div><strong>{sectionLabels[section.key]}</strong><small>{index + 1}번째 영역</small></div><label className="switch"><input type="checkbox" checked={section.enabled} onChange={() => { const sections = draft.home.sections.map((item) => item.key === section.key ? { ...item, enabled: !item.enabled } : item); patch("home", { ...draft.home, sections }); }} /><i /></label><button disabled={index === 0} onClick={() => moveSection(index, -1)}><ArrowUp /></button><button disabled={index === draft.home.sections.length - 1} onClick={() => moveSection(index, 1)}><ArrowDown /></button></article>)}</div></EditorGroup></>}
        <div className="cms-publish"><div className="cms-storage-status"><Check /><div><strong>편집 내용 준비됨</strong><span>로컬 저장은 이 기기만, 사이트 게시는 전체 사용자에게 반영됩니다.</span></div></div><button className="secondary" onClick={saveLocal}><Save /> 작업본 저장</button><label><LockKeyhole /><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="관리자 게시 비밀번호" /></label><button className="primary" disabled={publishing || !password} onClick={() => void publish()}>{publishing ? "게시 중..." : "사이트에 게시"}</button><p>{notice}</p></div>
      </section>
      <section className={`cms-preview device-${device}`}><header><div><Eye /> 실시간 미리보기</div><div><button className={device === "desktop" ? "selected" : ""} onClick={() => setDevice("desktop")}><Monitor /></button><button className={device === "mobile" ? "selected" : ""} onClick={() => setDevice("mobile")}><Smartphone /></button></div></header><div className="cms-preview-stage"><Preview config={draft} page={tab === "team" ? "team" : "home"} /></div></section></div>
    </section>
  </main>;
}

function EditorGroup({ title, children }: { title: string; children: React.ReactNode }) { return <section className="cms-editor-group"><h2>{title}</h2>{children}</section>; }
function TextField({ label, value, maxLength, onChange }: { label: string; value: string; maxLength?: number; onChange: (value: string) => void }) { return <label className="cms-field"><span>{label}</span><input value={value} maxLength={maxLength} onChange={(event) => onChange(event.target.value)} /></label>; }
function TextArea({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="cms-field"><span>{label}</span><textarea value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function ColorField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="cms-color"><span>{label}</span><div><input type="color" value={value} onChange={(event) => onChange(event.target.value)} /><input value={value} onChange={(event) => /^#[0-9a-f]{6}$/i.test(event.target.value) && onChange(event.target.value)} /></div></label>; }
function RangeField({ label, value, min, max, suffix, onChange }: { label: string; value: number; min: number; max: number; suffix: string; onChange: (value: number) => void }) { return <label className="cms-range"><span>{label}<b>{value}{suffix}</b></span><input type="range" value={value} min={min} max={max} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="cms-toggle"><span>{label}</span><label className="switch"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><i /></label></div>; }
function Preview({ config, page }: { config: SiteConfig; page: "home" | "team" }) {
  return <div className="cms-site-preview" style={{ background: config.theme.paper, color: config.theme.ink, borderRadius: config.theme.radius / 2, fontSize: `${config.theme.fontScale}%` }}><header><div><b style={{ background: config.theme.ink, color: config.theme.accent }}>{config.brand.mark}</b><strong>{config.brand.name}</strong></div><nav><span>{config.navigation.studio}</span><span>{config.navigation.team}</span></nav></header>{page === "home" ? <main><small style={{ color: config.theme.primary }}>{config.home.eyebrow}</small><h1>{config.home.title}<em style={{ color: config.theme.primary }}>{config.home.accentTitle}</em></h1><p>{config.home.description}</p><section style={{ background: config.theme.surface, borderRadius: config.theme.radius }}><div className="preview-input-row"><i /><i /></div><div className="preview-upload" style={{ borderColor: config.theme.primary }}><b style={{ color: config.theme.primary }}>↑</b><strong>{config.home.uploadTitle}</strong><small>{config.home.uploadDescription}</small></div></section><footer>{config.home.trustItems.map((item) => <span key={item}>✓ {item}</span>)}</footer></main> : <main className="cms-team-preview"><small style={{ color: config.theme.primary }}>{config.team.eyebrow}</small><h1>{config.team.title.split("\n").map((line) => <span key={line}>{line}</span>)}</h1><p>{config.team.description}</p><div className="preview-search">⌕ {config.team.searchPlaceholder}</div><article style={{ background: config.theme.surface, borderRadius: config.theme.radius }}><i style={{ background: config.theme.primary }}>A</i><div><small>팀원 구해요 · 모집 중</small><strong>새로운 무대를 함께할 연주자를 찾습니다</strong><span>연주 · 서울 · 협의</span></div></article></main>}</div>;
}
